target for gosec scan
google/shifter pull request #104
Opened 2022-08-10 09:18 UTC by parasmamgain

# Description

Added gosec scan as target to detect anu major vulnerability that can be detected and patched as and when required. This will also be incorporated in the CI/CD flow.

**Output :** A short snippet of expected output is shared below however a detailed output with issues detected will be logged in result.json file :

```Summary:
  Gosec  : 2.12.0
  Files  : 58
  Lines  : 4840
  Nosec  : 0
  Issues : 71
```
Fixes # (issue)

## Primary Components Effected

Please mark one option with an "x".

- [ ] Shifter (Core CLI and Server Application)
- [ ] Shifter UI (The Web Interface)
- [x] Cross Component Configuration (.github workflows, templates, docs, .MD files)

## Type of change

Please mark one option with an "x".

- [ ] #RELEASE New Collection of Features (containing breaking and non-breaking changes)
- [ ] #FT New feature (non-breaking change which adds functionality, imrproves performance or code quality)
- [ ] #BUG Bug Fix (non-breaking change which fixes an issue)
- [x] #PATCH Patch (non-breaking change which modifies only non-code object [Docs, Readme])

## Developer / Author Notes

Please feel free to provide any additional notes, content or context relating to this PR and subsequent contribution.

2022-08-10 10:34 UTC, garybowers commented
Can you add gosec to the runners also and to the pipeline?

2022-08-10 16:11 UTC, parasmamgain commented
Hi @garybowers ,
I have just added the changes, following is the link which had a succesful run when merged with master(forked repo)
Link : https://github.com/parasmamgain/shifter/actions/runs/2834017282

2022-08-10 18:26 UTC, garybowers reviewed
We are not using github actions but cloudbuild.  Please update the cloudbuild yaml :)

2022-08-10 18:26 UTC, garybowers requested changes
We are not using github actions but cloudbuild.  Please update the cloudbuild yaml :)

2022-08-11 14:14 UTC, parasmamgain commented on shifter/Makefile
> +	curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.12.0 && \
Just incorporate the changes discussed above.
- removed the installation from makefile
- additional step added in cloudbuild for the gosec scans
- tested the changes above and it did ran fine in my envt.

Please feel free to let me know if some-other changes are required. we can connect otherwise anytime :)

2022-08-11 14:19 UTC, garybowers approved these changes
LGTM!!!

2022-08-11 14:20 UTC, merged