Add basic github actions for CI workflow
google/shifter pull request #127
Opened 2022-09-22 15:17 UTC by umeshkumhar

# Description

This PR add some github actions that run CI jobs to validate the PR code by running some  required actions
Golang code - run go lint 
Vue & Npm code - run npm build & run lint

This is beneficial for the new contributors in raising PRs and since cloudbuild jobs are private to only Google employees. 

## Primary Components Effected

Please mark one option with an "x".

- [ ] Shifter (Core CLI and Server Application)
- [ ] Shifter UI (The Web Interface)
- [x] Cross Component Configuration (.github workflows, templates, docs, .MD files)

## Type of change

Please mark one option with an "x".

- [ ] #RELEASE New Collection of Features (containing breaking and non-breaking changes)
- [ ] #FT New feature (non-breaking change which adds functionality, improves performance or code quality)
- [ ] #BUG Bug Fix (non-breaking change which fixes an issue)
- [ ] #PATCH Patch (non-breaking change which modifies only non-code object [Docs, Readme])

## Developer / Author Notes

Please feel free to provide any additional notes, content or context relating to this PR and subsequent contribution.

2022-09-23 07:36 UTC, garybowers commented
We are not using giithub ci, could you please add this to cloudbuild instead.

2022-09-29 21:21 UTC, garybowers requested changes
Remove github actions and move to cloudbuild as this is the project strategic choice of CI.

2022-09-29 21:21 UTC, garybowers commented on shifter/shifter.go
> +
Why the added blank lines?

2022-09-29 21:21 UTC, garybowers commented on .github/workflows/golang-ci.yml
> +name: golang-ci
As mentioned earlier - we are not using github actions at all, this needs to be moved to the cloudbuild job

2022-09-29 21:21 UTC, garybowers commented on .github/workflows/npm-ci.yml
> +name: npm-ci-workflow
As mentioned earlier - we are not using github actions at all, this needs to be moved to the cloudbuild job

2022-10-07 04:40 UTC, umeshkumhar commented
> Remove github actions and move to cloudbuild as this is the project strategic choice of CI.

Hey @garybowers 

We discussed this actually, this is basically CI jobs for external contributors, since cloud build jobs are restricted to core collaborators only. If external contributor raises PR then there is no way to validate that his/her PR is in good state to review.

So we were thinking to have github actions for basic PR readiness jobs such as linting issues, gosec issues..

And for other testing pipeline and release pipeline we can still be on cloud build yamls.

Let me know your thoughts on this.

2022-10-07 04:42 UTC, umeshkumhar commented on shifter/shifter.go
> +
just testing out linting issues

2022-10-07 08:44 UTC, garybowers approved these changes
lgtm

2022-10-07 08:44 UTC, merged